;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="AbilitySystem.Ability.Crouch",DevComment="")
+GameplayTagList=(Tag="AbilitySystem.Ability.Jump",DevComment="")
+GameplayTagList=(Tag="AbilitySystem.Ability.Sprint",DevComment="")
+GameplayTagList=(Tag="AbilitySystem.AbilitySystemSet.Character",DevComment="")
+GameplayTagList=(Tag="Mover.Intent.Crouch",DevComment="")
+GameplayTagList=(Tag="Mover.Intent.Sprint",DevComment="")
+GameplayTagList=(Tag="Mover.SharedSettings.Gait.Sprint",DevComment="")

